language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

matrix:
  include:
    - os: linux

notifications:
  email: false

cache:
  directories:
    - $HOME/.bzrepos
    - $HOME/.cache/bazel

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get -u github.com/swaggo/swag/cmd/swag; go mod download; sudo apt-get update; sudo apt-get install rpm; sudo apt install snapd; sudo snap install skopeo --edge --devmode; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 60 make; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

